# Generated by Django 3.1.3 on 2021-01-12 20:49

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210112_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orignal_bag',
            new_name='original_bag',
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
