# Generated by Django 3.1.3 on 2020-12-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201230_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_size',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
